import { OBJECTIVE_TYPES, DIFFICULTY_LEVELS } from './missionTypes';

/**
 * Data-driven Mission Configurations for Chandrayaan-3 Vikram Lander Simulator
 */
export const MISSIONS = [
  {
    id: 'mission-1',
    number: 1,
    title: 'FIRST DESCENT',
    briefingTitle: 'VIKRAM LANDER TRAINING MISSION',
    description: 'Perform a controlled descent from 200m altitude and execute a soft touchdown inside the designated lunar landing zone.',
    difficulty: DIFFICULTY_LEVELS.EASY,
    startingAltitude: 200,
    startingFuelPercent: 100,
    landingZoneRadius: 15,
    restrictions: {
      disableScanner: false,
      disableGuidance: false,
    },
    objectives: [
      {
        id: 'obj-1-1',
        type: OBJECTIVE_TYPES.SAFE_LANDING,
        label: 'Execute a safe touchdown',
        mandatory: true,
      },
      {
        id: 'obj-1-2',
        type: OBJECTIVE_TYPES.LANDING_INSIDE_ZONE,
        label: 'Touch down inside target zone (≤ 15m)',
        targetValue: 15,
        mandatory: true,
      },
      {
        id: 'obj-1-3',
        type: OBJECTIVE_TYPES.MAX_TILT,
        label: 'Keep lander tilt ≤ 10°',
        targetValue: 10,
        mandatory: false,
      },
      {
        id: 'obj-1-4',
        type: OBJECTIVE_TYPES.MAX_TOUCHDOWN_SPEED,
        label: 'Descent speed ≤ 4.0 m/s',
        targetValue: 4.0,
        mandatory: false,
      },
    ],
  },
  {
    id: 'mission-2',
    number: 2,
    title: 'FUEL DISCIPLINE',
    briefingTitle: 'PROPELLANT CONSERVATION FLIGHT',
    description: 'Execute a smooth lunar landing while minimizing fuel burn. Maintain at least 40% propellant reserves upon touchdown.',
    difficulty: DIFFICULTY_LEVELS.NORMAL,
    startingAltitude: 300,
    startingFuelPercent: 100,
    landingZoneRadius: 12,
    restrictions: {
      disableScanner: false,
      disableGuidance: false,
    },
    objectives: [
      {
        id: 'obj-2-1',
        type: OBJECTIVE_TYPES.SAFE_LANDING,
        label: 'Execute a safe touchdown',
        mandatory: true,
      },
      {
        id: 'obj-2-2',
        type: OBJECTIVE_TYPES.LANDING_INSIDE_ZONE,
        label: 'Touch down inside target zone (≤ 12m)',
        targetValue: 12,
        mandatory: true,
      },
      {
        id: 'obj-2-3',
        type: OBJECTIVE_TYPES.MIN_REMAINING_FUEL,
        label: 'Maintain ≥ 40% propellant remaining',
        targetValue: 40,
        mandatory: true,
      },
      {
        id: 'obj-2-4',
        type: OBJECTIVE_TYPES.MAX_TILT,
        label: 'Keep lander tilt ≤ 10°',
        targetValue: 10,
        mandatory: false,
      },
    ],
  },
  {
    id: 'mission-3',
    number: 3,
    title: 'HAZARD AVOIDANCE',
    briefingTitle: 'CRATER & ROCK FIELD NAVIGATION',
    description: 'Navigate through a crater-dense sector. Use the Hazard Scanner to avoid rock collisions and steep crater slopes.',
    difficulty: DIFFICULTY_LEVELS.NORMAL,
    startingAltitude: 300,
    startingFuelPercent: 100,
    landingZoneRadius: 10,
    restrictions: {
      disableScanner: false,
      disableGuidance: false,
    },
    objectives: [
      {
        id: 'obj-3-1',
        type: OBJECTIVE_TYPES.SAFE_LANDING,
        label: 'Execute a safe touchdown',
        mandatory: true,
      },
      {
        id: 'obj-3-2',
        type: OBJECTIVE_TYPES.LANDING_INSIDE_ZONE,
        label: 'Touch down inside target zone (≤ 10m)',
        targetValue: 10,
        mandatory: true,
      },
      {
        id: 'obj-3-3',
        type: OBJECTIVE_TYPES.AVOID_MAJOR_COLLISION,
        label: 'Avoid major terrain & rock collisions',
        mandatory: true,
      },
      {
        id: 'obj-3-4',
        type: OBJECTIVE_TYPES.MAX_SLOPE,
        label: 'Landing slope ≤ 5.0°',
        targetValue: 5.0,
        mandatory: false,
      },
    ],
  },
  {
    id: 'mission-4',
    number: 4,
    title: 'PRECISION LANDING',
    briefingTitle: 'PINPOINT TARGET APPROACH',
    description: 'A tight landing perimeter requires high lateral control accuracy. Touch down within 6 meters of the target center.',
    difficulty: DIFFICULTY_LEVELS.HARD,
    startingAltitude: 350,
    startingFuelPercent: 100,
    landingZoneRadius: 6,
    restrictions: {
      disableScanner: false,
      disableGuidance: false,
    },
    objectives: [
      {
        id: 'obj-4-1',
        type: OBJECTIVE_TYPES.SAFE_LANDING,
        label: 'Execute a safe touchdown',
        mandatory: true,
      },
      {
        id: 'obj-4-2',
        type: OBJECTIVE_TYPES.MAX_TARGET_DISTANCE,
        label: 'Touch down within 6.0m of center',
        targetValue: 6.0,
        mandatory: true,
      },
      {
        id: 'obj-4-3',
        type: OBJECTIVE_TYPES.MAX_HORIZONTAL_SPEED,
        label: 'Horizontal drift ≤ 1.5 m/s',
        targetValue: 1.5,
        mandatory: false,
      },
      {
        id: 'obj-4-4',
        type: OBJECTIVE_TYPES.MAX_TOUCHDOWN_SPEED,
        label: 'Descent speed ≤ 3.0 m/s',
        targetValue: 3.0,
        mandatory: false,
      },
    ],
  },
  {
    id: 'mission-5',
    number: 5,
    title: 'ROUGH TERRAIN',
    briefingTitle: 'SLOPED SURFACE LANDING',
    description: 'The south pole landing area is covered in uneven ridges. Locate flat ground and keep surface tilt within strict limits.',
    difficulty: DIFFICULTY_LEVELS.HARD,
    startingAltitude: 400,
    startingFuelPercent: 100,
    landingZoneRadius: 8,
    restrictions: {
      disableScanner: false,
      disableGuidance: false,
    },
    objectives: [
      {
        id: 'obj-5-1',
        type: OBJECTIVE_TYPES.SAFE_LANDING,
        label: 'Execute a safe touchdown',
        mandatory: true,
      },
      {
        id: 'obj-5-2',
        type: OBJECTIVE_TYPES.LANDING_INSIDE_ZONE,
        label: 'Touch down inside target zone (≤ 8m)',
        targetValue: 8.0,
        mandatory: true,
      },
      {
        id: 'obj-5-3',
        type: OBJECTIVE_TYPES.MAX_SLOPE,
        label: 'Terrain slope ≤ 5.0°',
        targetValue: 5.0,
        mandatory: true,
      },
      {
        id: 'obj-5-4',
        type: OBJECTIVE_TYPES.MAX_TILT,
        label: 'Keep lander tilt ≤ 8°',
        targetValue: 8.0,
        mandatory: false,
      },
    ],
  },
  {
    id: 'mission-6',
    number: 6,
    title: 'LOW FUEL EMERGENCY',
    briefingTitle: 'EMERGENCY PROPELLANT DESCENT',
    description: 'An anomaly leaves Vikram with only 35% propellant at 250m altitude. Manage main throttle precisely to land safely.',
    difficulty: DIFFICULTY_LEVELS.HARD,
    startingAltitude: 250,
    startingFuelPercent: 35,
    landingZoneRadius: 10,
    restrictions: {
      disableScanner: false,
      disableGuidance: false,
    },
    objectives: [
      {
        id: 'obj-6-1',
        type: OBJECTIVE_TYPES.SAFE_LANDING,
        label: 'Execute a safe touchdown',
        mandatory: true,
      },
      {
        id: 'obj-6-2',
        type: OBJECTIVE_TYPES.LANDING_INSIDE_ZONE,
        label: 'Touch down inside target zone (≤ 10m)',
        targetValue: 10.0,
        mandatory: true,
      },
      {
        id: 'obj-6-3',
        type: OBJECTIVE_TYPES.MIN_REMAINING_FUEL,
        label: 'Land before fuel drops to 0%',
        targetValue: 0.1,
        mandatory: true,
      },
      {
        id: 'obj-6-4',
        type: OBJECTIVE_TYPES.MAX_TOUCHDOWN_SPEED,
        label: 'Descent speed ≤ 3.5 m/s',
        targetValue: 3.5,
        mandatory: false,
      },
    ],
  },
  {
    id: 'mission-7',
    number: 7,
    title: 'MANUAL DESCENT',
    briefingTitle: 'RAW TELEMETRY PILOTING',
    description: 'Sensor guidance and hazard scanner HUD assistance are disabled. Pilot Vikram using raw attitude and velocity telemetry.',
    difficulty: DIFFICULTY_LEVELS.EXPERT,
    startingAltitude: 400,
    startingFuelPercent: 80,
    landingZoneRadius: 10,
    restrictions: {
      disableScanner: true,
      disableGuidance: true,
    },
    objectives: [
      {
        id: 'obj-7-1',
        type: OBJECTIVE_TYPES.SAFE_LANDING,
        label: 'Execute a safe touchdown',
        mandatory: true,
      },
      {
        id: 'obj-7-2',
        type: OBJECTIVE_TYPES.LANDING_INSIDE_ZONE,
        label: 'Touch down inside target zone (≤ 10m)',
        targetValue: 10.0,
        mandatory: true,
      },
      {
        id: 'obj-7-3',
        type: OBJECTIVE_TYPES.MAX_TILT,
        label: 'Keep lander tilt ≤ 8°',
        targetValue: 8.0,
        mandatory: true,
      },
      {
        id: 'obj-7-4',
        type: OBJECTIVE_TYPES.MAX_TOUCHDOWN_SPEED,
        label: 'Descent speed ≤ 3.5 m/s',
        targetValue: 3.5,
        mandatory: false,
      },
    ],
  },
  {
    id: 'mission-8',
    number: 8,
    title: 'SHIV SHAKTI',
    briefingTitle: 'CHANDRAYAAN-3 FINAL LANDING POINT',
    description: 'The ultimate mission: 500m descent, 45% starting fuel, 5m target radius, manual HUD mode, and steep terrain.',
    difficulty: DIFFICULTY_LEVELS.EXPERT,
    startingAltitude: 500,
    startingFuelPercent: 45,
    landingZoneRadius: 5,
    restrictions: {
      disableScanner: true,
      disableGuidance: true,
    },
    objectives: [
      {
        id: 'obj-8-1',
        type: OBJECTIVE_TYPES.SAFE_LANDING,
        label: 'Execute a safe touchdown',
        mandatory: true,
      },
      {
        id: 'obj-8-2',
        type: OBJECTIVE_TYPES.MAX_TARGET_DISTANCE,
        label: 'Pinpoint landing within 5.0m',
        targetValue: 5.0,
        mandatory: true,
      },
      {
        id: 'obj-8-3',
        type: OBJECTIVE_TYPES.MIN_REMAINING_FUEL,
        label: 'Maintain ≥ 5% propellant remaining',
        targetValue: 5.0,
        mandatory: true,
      },
      {
        id: 'obj-8-4',
        type: OBJECTIVE_TYPES.MAX_TILT,
        label: 'Keep lander tilt ≤ 6°',
        targetValue: 6.0,
        mandatory: true,
      },
      {
        id: 'obj-8-5',
        type: OBJECTIVE_TYPES.MAX_TOUCHDOWN_SPEED,
        label: 'Descent speed ≤ 3.0 m/s',
        targetValue: 3.0,
        mandatory: false,
      },
    ],
  },
];
